print('{} DESAFIO 26 {}'.format(('='*5), ('='*5)))
frase = str(input('Escreva uma frase: ')).upper().strip()
print('A letra A aparece {} vezes na frase'.format(frase.count('A')))
print('A letra A aparece pela primeira vez na posição {}'.format(frase.find('A')+1))
print('A letra A apareceu pela ultimavez na posição {}'.format(frase.rfind('A')+1))
